name: Own Workflow

on: push

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
    - run: echo Hello World
    - run: date
  windows:
    runs-on: windows-latest
    steps:
    - run: date
  macos:
    needs: [ubuntu, windows]
    runs-on: macos-latest
    steps:
    - run: date
    
